source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

xcodeproj 'GTAppUpdater'
use_frameworks!


target 'GTAppUpdater_Example' do
  pod 'GTAppUpdater', :path => '../'
end

target 'GTAppUpdater_Tests' do
  pod 'GTAppUpdater', :path => '../'

  
end
